openapi: "3.0.0"
info:
  version: 1.0.0
  title: ARCHS4 Data API
  description: An API for grabbing subsets of the ARCHS4 data file.
  # termsOfService:
  contact:
    name: Ma'ayan Lab
    # email: 
    url: https://maayanlab.cloud/
  license:
    name: CC-BY-NC-SA
    url: https://github.com/MaayanLab/archs4-api/blob/main/LICENSE
servers:
  - url: /
paths:
  /:
    get:
      description: |
        This openapi spec, visit /ui for UI version.
      operationId: openapi
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
  /openapi.json:
    get:
      description: |
        This openapi spec, visit /ui for UI version.
      operationId: openapi.json
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
  /openapi.yaml:
    get:
      description: |
        This openapi spec, visit /ui for UI version.
      operationId: openapi.yaml
      responses:
        '200':
          description: success
          content:
            application/x-yaml:
              schema:
                type: string
            text/yaml:
              schema:
                type: string
  /data/expression:
    post:
      description: |
        Returns sample data from the ARCHS4 Matrix. Max 100 at a time
      operationId: fetch_data_expression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                geo_accession:
                  description: GEO Accessions to get the Data for
                  type: array
                  items:
                    type: string
                genes:
                  description: A set of specific genes to select
                  type: array
                  items:
                    type: string
              required:
                - geo_accession
            example:
              geo_accession: ["GSM4615036"]
              genes: ["ACE2"]
      responses:
        '200':
          description: |
            Object of the form {sample: {gene: expression, ...}, ...}
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    type: integer
            text/tab-separated-values:
              schema:
                type: string
        '404':
          description: Query resulted in an empty matrix because of missing samples/genes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /data/expression/T:
    post:
      description: |
        Returns sample data from the ARCHS4 Matrix transposed, streaming
      operationId: fetch_data_expression_transpose
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                geo_accession:
                  description: GEO Accessions to get the Data for
                  type: array
                  items:
                    type: string
                genes:
                  description: A set of specific genes to select
                  type: array
                  items:
                    type: string
              required:
                - geo_accession
            example:
              geo_accession: ["GSM4615036"]
              genes: ["ACE2"]
      responses:
        '200':
          description: |
            TSV of the form:
                  \t gene1      \t gene2      \t ...\n
            GSE1  \t expression \t ...        \t ...\n
            ...
          content:
            text/tab-separated-values:
              schema:
                type: string
        '404':
          description: Query resulted in an empty matrix because of missing samples/genes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /meta/samples/geo_accession:
    get:
      description: |
        Returns sample geo accession ids from the ARCHS4 Matrix.
      operationId: fetch_meta_samples_geo_accession
      parameters:
        - in: query
          name: q
          description: String to filter samples by
          schema:
            type: string
        - in: query
          name: series_id
          description: Filter samples contained in this series_id
          schema:
            type: string
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
            minimum: 0
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 10000
      responses:
        '200':
          description: |
            List of geo_accession ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
          headers:
            Content-Range:
              schema:
                type: string
                example: 0-100/2000
        '404':
          description: Query resulted in an empty list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /meta/genes/gene_symbol:
    get:
      description: |
        Returns gene symbols from the ARCHS4 Matrix.
      operationId: fetch_meta_genes_gene_symbol
      parameters:
        - in: query
          name: q
          description: String to filter genes by
          schema:
            type: string
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
            minimum: 0
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 10000
      responses:
        '200':
          description: |
            List of gene_symbol ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
          headers:
            Content-Range:
              schema:
                type: string
                example: 0-100/2000
        '404':
          description: Query resulted in an empty list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /meta/samples/series_id:
    get:
      description: |
        Returns study identifiers from the ARCHS4 Matrix.
      operationId: fetch_meta_samples_series_id
      parameters:
        - in: query
          name: q
          description: String to filter studies by
          schema:
            type: string
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
            minimum: 0
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 10000
      responses:
        '200':
          description: |
            List of geo_accession ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
          headers:
            Content-Range:
              schema:
                type: string
                example: 0-100/2000
        '404':
          description: Query resulted in an empty list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
